name: Maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: pahana_edu
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_URL: jdbc:mysql://127.0.0.1:3306/pahana_edu
      DB_USER: root
      DB_PASS: root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Wait for MySQL to start
        run: sleep 20  # gives MySQL time to be ready

      - name: Initialize database schema
        run: |
          mysql -h 127.0.0.1 -u $DB_USER -p$DB_PASS $MYSQL_DATABASE < sql/schema.sql
          mysql -h 127.0.0.1 -u $DB_USER -p$DB_PASS $MYSQL_DATABASE < sql/test-data.sql

      - name: Build and test with Maven
        run: mvn clean test
